:arrow_up: Bumps to kivy post 2.0.0rc2 on Android
Note we couldn't pin to `2.0.0rc2` as it's failing runtime with:
```
Run user program, change dir and execute entrypoint
 Traceback (most recent call last):
   File "/home/user/hostcwd/.buildozer/android/app/main.py", line 5, in <module>
   File "/home/user/hostcwd/.buildozer/android/app/kivy_garden/xcamera/__init__.py", line 15, in <module>
   File "/home/user/hostcwd/.buildozer/android/app/kivy_garden/xcamera/xcamera.py", line 4, in <module>
   File "/home/user/hostcwd/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/xcamera/kivy/__init__.py", line 351, in <module>
 PermissionError: [Errno 13] Permission denied: '/data/.kivy'
Python for android ended.
```
This was fixed post rc2 via <https://github.com/kivy/kivy/pull/6852>