Python3 compatible print function
Follow up for #4 
In some cases building for host/target python3 was failing with the following:
```
Compiling '/home/andre/workspace/.buildozer/android/app/libs/garden/garden.xcamera/example/main.py'...
***   File "/home/andre/workspace/.buildozer/android/app/libs/garden/garden.xcamera/example/main.py", line 35
    print 'Picture taken and saved to', filename
                                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Picture taken and saved to', filename)?
```